### ISSUE TITLE
eSchoolUpload: File uploaded with no data

### ISSUE THREAD

**Issue by VinVar** [AR-k12code/eSchoolUpload#21]
We are getting the below error on the eschoolPlusUpload.ps1 file. 
Error: Failed to upload file to eSchool. eSchoolPlus
Display Notifications Viewer View Favorites

File gets created in eSchoolPlus but with 0 bytes. File to be uploaded exists with data. 

Thank you.

**Comment by carbm1** [comment]
What Powershell version are you running?

$PSVersionTable

Can you share a sample of the data you're trying to upload?  You can share it to my school account cmillsap@gentrypioneers.com

**Comment by VinVar** [comment]
Thank you for your response. I am using  PSVersion  5.1.19041.1237
 
 My mistake. I was able to get it to work by changing $template to below.
$template = @'
--{0}
Content-Disposition: form-data; name="fileData"; filename="{1}"
Content-Type: {2}

{3}
--{0}--

'@

**Comment by carbm1** [comment]
While reviewing your response what you posted is identical to what as in the file already.

I did find an error using Powershell 5.1 that kept files from being uploaded though. We just pushed a new version that hopefully will fix that for you.
